name: Linux Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      PYTEST_ADDOPTS: --color=yes
    strategy:
      matrix:
        os: ['ubuntu-20.04']

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install colorama pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Run SCons unit tests
#        run: |
#          python runtest.py -a -j 2 --unit-only
      - name: Run pytest
        run: |
          FIXTURE_DIRS=test/fixture PYTHONPATH=testing/framework python3 -m pytest
      - name: Run SCons E2E tests
        run: |
          python runtest.py -a -j 2 --e2e-only

# vim: ts=2:sw=2:et
